services:
  # ----- Backend (FastAPI) -----
  services:
  - type: web
    name: disease-backend
    env: python
    rootDir: Backend
    buildCommand: |
      apt-get update && apt-get install -y git git-lfs
      git lfs install
      git lfs pull
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000


  # ----- Frontend (React Vite) -----
  - type: web
    name: bank-frontend
    env: node
    plan: free
    buildCommand: "cd Frontend && npm install && npm run build"
    startCommand: "npx serve -s bank-frontend/dist -l 3000"
